// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXN5KHVhzCvlEYyoasO3mYzNrPS9YmiZQ',
    appId: '1:1041233032586:web:acacdda3e00272f3ef0473',
    messagingSenderId: '1041233032586',
    projectId: 'appointify-388715',
    authDomain: 'appointify-388715.firebaseapp.com',
    storageBucket: 'appointify-388715.appspot.com',
    measurementId: 'G-ELV52Z1S3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNSdThFPWSG3Jpn_5W1X0Qmmf_yLWWQW8',
    appId: '1:1041233032586:android:7972379d8225891bef0473',
    messagingSenderId: '1041233032586',
    projectId: 'appointify-388715',
    storageBucket: 'appointify-388715.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBezR_Eac2v8KmH4PbWLI3dCNwHEHjZ_Lo',
    appId: '1:1041233032586:ios:b1624dd40661a9cfef0473',
    messagingSenderId: '1041233032586',
    projectId: 'appointify-388715',
    storageBucket: 'appointify-388715.appspot.com',
    iosClientId: '1041233032586-flk3o9731qguo4v0i8hj355p0nltiqdb.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBezR_Eac2v8KmH4PbWLI3dCNwHEHjZ_Lo',
    appId: '1:1041233032586:ios:96139ca67ed7a093ef0473',
    messagingSenderId: '1041233032586',
    projectId: 'appointify-388715',
    storageBucket: 'appointify-388715.appspot.com',
    iosClientId: '1041233032586-te4866gbleeilaac7ls3nam87gmu2nuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointify.RunnerTests',
  );
}
